hw_quotes/hw_quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw_quotes/users/urls.py
from django.contrib.auth.views import (PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path("reset-password/done/",
         PasswordResetDoneView.as_view(
             template_name="users/password_reset_done.html"
         ),
         name="password_reset_done"),

    path("reset-password/confirm/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url="/users/reset-password/complete/"),
         name="password_reset_confirm"),

    path("reset-password/complete/",
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

]

hw_quotes/users/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="profile_images", default="avatar.png")

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.avatar.path)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

hw_quotes/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Profile


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True)
    password1 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password"}
        )
    )

    password2 = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Confirm Password"}
        )
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password")

class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ["avatar"]

hw_quotes/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import SignUpForm, LoginForm, ProfileForm


# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == "POST":
        user = authenticate(
            username=request.POST["username"],
            password=request.POST["password"]
        )
        if user is None:
            messages.error(request, "Invalid username or password")
            return redirect(to="users:login")

        login(request, user)
        return redirect("/")

    return render(request, "users/login.html", context={"form": LoginForm()})


@login_required
def logout_view(request):
    logout(request)
    return redirect("/")


def signup_view(request):
    if request.user.is_authenticated:
        return redirect("/")

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
        else:
            return render(request, "users/signup.html", context={"form": form})

    return render(request, "users/signup.html", context={"form": SignUpForm()})


def profile_view(request):
    if request.method == "POST":
        profile_form = ProfileForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, "Profile updated")
            return redirect(to="users:profile")

    profile_form = ProfileForm(instance=request.user.profile)
    return render(
        request,
        "users/profile.html",
        context={"profile_form": profile_form}
    )


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = "Check your email to reset your password"
    subject_template_name = "users/password_reset_subject.txt"

hw_quotes/users/templates/users/login.html
{% extends 'quotes/base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
{% if messages %}
<div>
    {% for message in messages %}
    <div %} %} class="alert-{{ message.tags }}" endif if message.tags {% {%>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% if request.path != '/users/login/' %}
<p>Please login to get access to all the features</p>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:<br>
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:<br>
            {{ form.password }}
        </label>
    </div>

    <div style="flex: auto; margin-top: 10px">
        <button class="tag" type="submit">Submit</button>
        <button class="tag" type="reset">Reset</button>
    </div>

    <div class="small text-center">
        <a class="text-center" href="{% url 'users:password_reset' %}"><i>Forgot password?</i></a>

    </div>
</form>
{% endblock %}

hw_quotes/users/templates/users/logout.html
{% extends 'quotes/base.html' %}
{% block title %}Logout{% endblock %}
{% block content %}
<h1>Logout</h1>
{% endblock %}

hw_quotes/users/templates/users/password_reset.html
{% extends 'quotes/base.html' %}
{% load static %}
{% block title %}Password reset{% endblock %}
{% block content %}
<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset password reset</button>
</form>
{% endblock %}

hw_quotes/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hw_quotes/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hw_quotes/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hw_quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hw_quotes/users/templates/users/profile.html
{% extends "quotes/base.html" %}

{% block content %}
<div>
    <h2>Profile page: {{user.username}}</h2><br>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form class="container" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-1">Change Avatar:</label><br>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <br>

    <div class="grid">
        <button type="submit">Save Changes</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>
{% endblock %}

hw_quotes/users/templates/users/signup.html
{% extends 'quotes/base.html' %}
{% load static %}
{% block title %}Signup{% endblock %}
{% block content %}
<div>
    <h2>Sign Up</h2>
</div>

<form action="{% url 'users:signup' %}" method="post">
    {% csrf_token %}
    <div class="form-group mb-3">
        <label> Username:</label><br>
        {{ form.username }}
        <span>{{ form.errors.username }}</span>
    </div>
    <div class="form-group mb-3">
        <label> Email:<br>
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>

    <br>
    <div class="form-group mb-3">
        <label> Password:<br>
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div class="form-group mb-3">
        <label> Password confirmation:<br>
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button class="tag" type="submit">Submit</button>
        <button class="tag" type="reset">Reset</button>
    </div>
</form>
{% endblock %}