hw_quotes/hw_quotes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw_quotes/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="index_page"),
    path("details/<author_id>/", views.details, name="author_details"),
    path("authors/", views.author_list, name="author_list"),
    path("tag/<tag>", views.tag_list, name="tag_list"),
    path("add_author/", views.add_author, name="add_author"),
    path("add_quote/", views.add_quote, name="add_quote"),
]

hw_quotes/users/urls.py
from django.contrib.auth.views import (PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path("reset-password/done/",
         PasswordResetDoneView.as_view(
             template_name="users/password_reset_done.html"
         ),
         name="password_reset_done"),

    path("reset-password/confirm/<uidb64>/<token>/",
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url="/users/reset-password/complete/"),
         name="password_reset_confirm"),

    path("reset-password/complete/",
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name="password_reset_complete"),

]

hw_quotes/quotes/models.py
from django.db import models


# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=100, unique=True)
    born_date = models.CharField(max_length=100)
    born_location = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(
        Author, null=True, on_delete=models.CASCADE, default=None
    )
    tags = models.ManyToManyField("Tag")


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

hw_quotes/quotes/forms.py
from django import forms

from .models import Author, Quote, Tag


class AuthorForm(forms.ModelForm):
    fullname = forms.CharField(max_length=100)
    born_date = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)
    born_location = forms.CharField(max_length=100)

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'selectpicker'}),
        label="Choose tags"

    )

    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        widget=forms.Select(attrs={'class': 'selectpicker'}),
        label="Choose author")

    text = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3}),
        label="Quote text"
    )

    class Meta:
        model = Quote
        fields = ["text", "author", "tags"]

hw_quotes/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from .forms import QuoteForm, AuthorForm
from .models import Quote, Author, Tag  # Імпортуємо моделі Django


def main(request, page=1):
    quotes = Quote.objects.all().prefetch_related("tags")  # Використовуємо модель Quote замість db.quotes.find()

    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page})


def details(request, author_id):
    author = Author.objects.get(pk=author_id)  # Використовуємо модель Author замість db.authors.find_one()

    print(author.fullname)
    return render(request, "quotes/author_details.html", context={"author": author})


def author_list(request):
    authors = Author.objects.all()
    return render(request, "quotes/authors.html", context={"authors": authors})


def tag_list(request, tag):
    tag = Tag.objects.get(name=tag)
    quotes = Quote.objects.filter(tags=tag)

    return render(
        request, "quotes/quotes_by_tag.html", context={"quotes": quotes, "tag": tag}
    )


@login_required()
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save()
            return redirect("quotes:author_list")
        else:
            print(form.errors)
    else:
        form = AuthorForm()
    return render(request, "quotes/add_author.html", {"form": form})


@login_required
def add_quote(request):
    form = QuoteForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            new_quote = form.save()
            return redirect("/")
    return render(request, "quotes/add_quote.html", {"form": form})

hw_quotes/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}
{% block title %}Add Author{% endblock %}
{% block content %}
<h2>Add Author</h2>
<form action=" {% url 'quotes:add_author' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}
{% block title %}Add Quote{% endblock %}

{% block content %}
<h1>Add your Quote</h1>
<form action=" {% url 'quotes:add_quote' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/author_details.html
{% extends 'quotes/base.html' %}


{% block title %}
author details
{% endblock %}

{% block content %}
<h1>{{ author.fullname}}</h1>
<p> {{ author.fullname }} was born on {{ author.born_date }}</p>
<p> in {{ author.born_location }}</p>
<p> {{ author.description }}</p>
<a href="/authors/">back to authors</a>
{% endblock %}

hw_quotes/quotes/templates/quotes/authors.html
{% extends 'quotes/base.html' %}
{% load my_filters %}

{% block title %}
authors
{% endblock %}
{% block content %}
<h1 style="text-align: center">Authors</h1>
<div style="margin-bottom: 100px">
    <ol>
        {% for author in authors %}

        <li class="quote"><h4>{{ author.fullname }}</h4><a href="/details/{{ author.id }}">(about)</a><br></li>
        {% endfor %}
    </ol>
</div>
{% endblock %}

hw_quotes/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" rel="stylesheet">
    {% load static %}
    <link href="{% static 'quotes/style.css' %}" rel="stylesheet">
    <link href="{% static 'quotes/kiss.png' %}" rel="icon" type="image/x-icon">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    <div class="row header-box">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            {% if user.is_authenticated %}
            <div class="d-flex justify-content-between">

                <div class="d-flex flex-column">

                    <div class="tag">
                        <a href="/add_quote/">Add a Quote</a>
                    </div>

                    <br>

                    <div class="tag">
                        <a href="/add_author/">Add an Author</a>
                    </div>

                </div>


                <div>
                    <a href="/users/profile/">
                        <img src="{{user.profile.avatar.url}}" style="width:36px"><br>{{ user.username }}
                    </a>
                </div>

                <a href="/users/logout/">Signout</a>

            </div>

            {% elif user.is_anonymous %}
            <p>
                <a href="/users/login/">Login</a> or
                <a href="/users/signup/">Signup</a>
            </p>
            {% endif %}
        </div>
    </div>
    {% block content %}{% endblock %}


</div>

<footer class="footer">
    <div class="container">
        <p class="text-muted">
            Quotes by: <a href="https://www.goodreads.com/quotes">GoodReads.com</a>
        </p>
        <p class="copyright">
            Made with <span><img alt="kiss" src=" {% static 'quotes/kiss.png' %}" style="width: 36px"></span> by <a
                href="https://www.linkedin.com/in/sergiy-koval-14b0a212/">the10or</a>
        </p>
    </div>
</footer>

</body>
</html>

hw_quotes/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block title %}
index
{% endblock %}

{% block content %}


<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.text  }}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>

        <a href="/details/{{quote.author.id}}" previewlistener="true">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <span class="tag">
                    <a href="/tag/{{tag.name}}" previewlistener="true">{{ tag.name }}</a>
                </span>
                {% endfor %}

            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="pager-item previous" style="float: left">
                    <a class="{% if not quotes.has_previous %}disabled{% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:index_page' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous</a>
                </li>


                <li class="pager-item next" style="float: right">
                    <a class="{% if not quotes.has_next %}disabled{% endif %}"
                       href=" {% if quotes.has_next %} {% url 'quotes:index_page' quotes.next_page_number %} {% else %} # {% endif %}"
                       previewlistener="true">
                        Next <span aria-hidden="true">→</span>
                    </a>


                </li>


            </ul>
        </nav>
    </div>
</div>


{% endblock %}

hw_quotes/quotes/templates/quotes/quotes_by_tag.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block title %}
quotes by tag
{% endblock %}

{% block content %}
<h3 style="text-align: left; margin-left: 30px;"><b>Viewing tag: <p style="display: inline; color: #4582ec" >{{ tag.name }}</p></b></h3>
<ul>
     {% for quote in quotes.all %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{ quote.text }}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>

        <a href="/details/{{quote.author.id}}" previewlistener="true">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <span class="tag">
                    <a href="/tag/{{tag.name}}" previewlistener="true">{{ tag.name }}</a>
                </span>
                {% endfor %}

            </div>
        </div>

        {% endfor %}

</ul>

{% endblock %}